on:
  push:
    branches:
      - main
 
jobs:
  list-s3-buckets:
    name: List S3 Buckets
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1      
      - name: List S3 buckets
        run: |
          aws sts get-caller-identity
          aws ec2 describe-instances

