name: list s3 buckets
on:
  push:
    branches:
      - main 
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Set AWS credentials
        run: |
          aws configure set aws_access_key_id AKIAYS2NR5CB7XSFXTFE
          aws configure set aws_secret_access_key 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
          aws configure set default.region eu-north-1
          aws
          

